### ISSUE TITLE
api must be simple

### ISSUE THREAD

**Issue by zaneck** [arctarus44/Simple_Chart#3]
Lines and Area points belong to a subset. Dots did not. It's not a correct way to do.
Dots may belong to a subset too. 

thx u a lot for the tee!

**Comment by arctarus44** [comment]
I add subsets handling for the DotsHandler class.

Now, if you want to display your data with dots or lines, you just have to change the inheritance tree by using/creating a class that handle the right display.

You can test/check it on the issue3 branch.

**Comment by arctarus44** [comment]
Merge done
